title: Olga  Gavrik 

logo: /images/picture.png

description:
 <a href="https://www.linkedin.com/in/olga-gavrik-87871a2b4">LinkedIn</a> |
 <a href="https://github.com/olgagavrik">GitHub</a>
 

theme: jekyll-theme-minimal
colors:
  crimson: '#900C3F'
